services:
  postgres_weather:
    container_name: postgres_weather
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    ports:
      - "5433:5432"
    volumes:
      - ${VOLUME_PATH}:/var/lib/postgresql/data

  weather_etl:
    container_name: weather_etl
    build: ${BUILD_PATH}
    restart: unless-stopped
    environment:
      - DB_HOST=postgres_weather
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - TZ=${TZ}
      - LATITUDE=${LATITUDE}
      - LONGITUDE=${LONGITUDE}
    depends_on:
      - postgres_weather
